In [1]:
import pandas as pd
import numpy as np
pd.options.display.float_format = "{:.2f}".format

In [11]:
np.set_printoptions(precision=1)

In [13]:
x1 = np.random.rand(2, 5) * 10
x1

array([[5. , 5.4, 5.8, 0.5, 1.2],
       [6.4, 7.9, 5.7, 5.9, 8.1]])

In [9]:
x2 = np.random.rand(2, 5) * -1
x2

array([[-0.06, -0.42, -0.33, -0.44, -0.03],
       [-0.46, -0.16, -0.51, -0.05, -0.48]])

In [19]:
np.concatenate([x1,x2], axis=1)

array([[ 5. ,  5.4,  5.8,  0.5,  1.2, -0.1, -0.4, -0.3, -0.4, -0. ],
       [ 6.4,  7.9,  5.7,  5.9,  8.1, -0.5, -0.2, -0.5, -0. , -0.5]])

In [20]:
s1 = pd.Series(x1[0], index=['A', 'B', 'C', 'D', 'E'])
s1

A   5.01
B   5.38
C   5.76
D   0.49
E   1.20
dtype: float64

In [21]:
s2 = pd.Series(x2[0], index=['C', 'D', 'E', 'F', 'G'])
s2

C   -0.06
D   -0.42
E   -0.33
F   -0.44
G   -0.03
dtype: float64

In [23]:
pd.concat([s1, s2], axis=1)

0     1
A 5.01   NaN
B 5.38   NaN
C 5.76 -0.06
D 0.49 -0.42
E 1.20 -0.33
F  NaN -0.44
G  NaN -0.03

In [25]:
s1.reset_index(drop=True)

0   5.01
1   5.38
2   5.76
3   0.49
4   1.20
dtype: float64

In [26]:
pd.concat([s1.reset_index(drop=True), s2.reset_index(drop=True)], axis=1)

0     1
0 5.01 -0.06
1 5.38 -0.42
2 5.76 -0.33
3 0.49 -0.44
4 1.20 -0.03

In [27]:
df1 = pd.DataFrame(np.random.rand(3, 2) * 10, columns=['A', 'B'])
df1

A    B
0 7.74 5.81
1 0.98 6.44
2 4.88 5.04

In [32]:
df2 = pd.DataFrame(np.random.rand(3, 2) * 1, columns=['A', 'B'], index=[2, 3, 4])
df2

A    B
2 0.13 0.74
3 0.90 0.05
4 0.51 0.92

In [33]:
pd.concat([df1, df2])

A    B
0 7.74 5.81
1 0.98 6.44
2 4.88 5.04
2 0.13 0.74
3 0.90 0.05
4 0.51 0.92

In [34]:
pd.concat([df1, df2], axis=1)

A    B    A    B
0 7.74 5.81  NaN  NaN
1 0.98 6.44  NaN  NaN
2 4.88 5.04 0.13 0.74
3  NaN  NaN 0.90 0.05
4  NaN  NaN 0.51 0.92

In [40]:
pd.concat([df1, df2], axis=1, join='inner')

A    B    A    B
2 4.88 5.04 0.13 0.74

In [41]:
pd.concat([df1.reset_index(drop=True), df2.reset_index(drop=True)], axis=1)

A    B    A    B
0 7.74 5.81 0.13 0.74
1 0.98 6.44 0.90 0.05
2 4.88 5.04 0.51 0.92

In [42]:
df1.append(df2).append(df2)

A    B
0 7.74 5.81
1 0.98 6.44
2 4.88 5.04
2 0.13 0.74
3 0.90 0.05
4 0.51 0.92
2 0.13 0.74
3 0.90 0.05
4 0.51 0.92

In [43]:
df1.T

0    1    2
A 7.74 0.98 4.88
B 5.81 6.44 5.04

In [46]:
df1.T.append(df2.T).T

A    B    A    B
0 7.74 5.81  NaN  NaN
1 0.98 6.44  NaN  NaN
2 4.88 5.04 0.13 0.74
3  NaN  NaN 0.90 0.05
4  NaN  NaN 0.51 0.92